/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NaudojimosiSalygosRouteImport } from './routes/naudojimosi-salygos'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCronEnaPricesRouteImport } from './routes/api/public/cron/ena-prices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NaudojimosiSalygosRoute = NaudojimosiSalygosRouteImport.update({
  id: '/naudojimosi-salygos',
  path: '/naudojimosi-salygos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronEnaPricesRoute = ApiPublicCronEnaPricesRouteImport.update({
  id: '/api/public/cron/ena-prices',
  path: '/api/public/cron/ena-prices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apie': typeof ApieRoute
  '/auth': typeof AuthRoute
  '/naudojimosi-salygos': typeof NaudojimosiSalygosRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/cron/ena-prices': typeof ApiPublicCronEnaPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apie': typeof ApieRoute
  '/auth': typeof AuthRoute
  '/naudojimosi-salygos': typeof NaudojimosiSalygosRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/cron/ena-prices': typeof ApiPublicCronEnaPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apie': typeof ApieRoute
  '/auth': typeof AuthRoute
  '/naudojimosi-salygos': typeof NaudojimosiSalygosRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/cron/ena-prices': typeof ApiPublicCronEnaPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apie'
    | '/auth'
    | '/naudojimosi-salygos'
    | '/privatumo-politika'
    | '/admin'
    | '/api/public/cron/ena-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apie'
    | '/auth'
    | '/naudojimosi-salygos'
    | '/privatumo-politika'
    | '/admin'
    | '/api/public/cron/ena-prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apie'
    | '/auth'
    | '/naudojimosi-salygos'
    | '/privatumo-politika'
    | '/_authenticated/admin'
    | '/api/public/cron/ena-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApieRoute: typeof ApieRoute
  AuthRoute: typeof AuthRoute
  NaudojimosiSalygosRoute: typeof NaudojimosiSalygosRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ApiPublicCronEnaPricesRoute: typeof ApiPublicCronEnaPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naudojimosi-salygos': {
      id: '/naudojimosi-salygos'
      path: '/naudojimosi-salygos'
      fullPath: '/naudojimosi-salygos'
      preLoaderRoute: typeof NaudojimosiSalygosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/ena-prices': {
      id: '/api/public/cron/ena-prices'
      path: '/api/public/cron/ena-prices'
      fullPath: '/api/public/cron/ena-prices'
      preLoaderRoute: typeof ApiPublicCronEnaPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApieRoute: ApieRoute,
  AuthRoute: AuthRoute,
  NaudojimosiSalygosRoute: NaudojimosiSalygosRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ApiPublicCronEnaPricesRoute: ApiPublicCronEnaPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
